<?php

namespace AppBundle\Repository;

/**
 * UniversityFeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniversityFeedbackRepository extends \Doctrine\ORM\EntityRepository
{
}
