app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

page_render_routes:
  resource: "routing/Page_render/page_rendering_routes.yml"
  type: yaml

comment_routes:
  resource: "routing/Comments/commenting_routes.yml"
  type: yaml

form_routes:
  prefix: /form
  type: yaml
  resource: "routing/Forms/comment_form_routes.yml"
