app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

about_page:
  path: /about
  defaults: {_controller: AppBundle:AboutPage:show }

feedback_page:
  path: /feedback
  defaults: {_controller: AppBundle:FeedbackPage:show }

universities_page:
  path: /universities
  defaults: {_controller: AppBundle:UniversitiesPage:show }