parameters:
services:
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Категории постов }
    
    admin.city:
        class: AppBundle\Admin\CityAdmin
        arguments: [~, AppBundle\Entity\City, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Города}

    admin.region:
        class: AppBundle\Admin\RegionAdmin
        arguments: [~, AppBundle\Entity\Region, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Регионы}

    admin.university:
        class: AppBundle\Admin\UniversityAdmin
        arguments: [~, AppBundle\Entity\University, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Университеты}

    admin.faculty:
        class: AppBundle\Admin\FacultyAdmin
        arguments: [~, AppBundle\Entity\Faculty, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Факультеты}

    admin.post:
        class: AppBundle\Admin\PostAdmin
        arguments: [~, AppBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Посты }
            
    admin.image:
        class: AppBundle\Admin\ImageAdmin
        arguments: [~, AppBundle\Entity\Image, 'SonataAdminBundle:CRUD']
        tags:
            - { name: sonata.admin, manager_type: orm, label: Изображения }
        calls:
            - [ setTranslationDomain, [AppBundle]]

    admin.subject:
        class: AppBundle\Admin\SubjectAdmin
        arguments: [~, AppBundle\Entity\Subject, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Предметы}
